let g:airline_powerline_fonts = 1
let g:airline_theme='powerlineish'
let g:airline_detect_spelllang = 0
let g:airline_detect_spell = 0
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#tmuxline#enabled = 1
let laststatus=2
